# Generated by Django 4.2.6 on 2023-10-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPage', '0002_blogcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcontent',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
