# Generated by Django 4.2.6 on 2023-10-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPage', '0004_blogcontent_slug_alter_blogcontent_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcontent',
            name='slug',
        ),
        migrations.AlterField(
            model_name='blogcontent',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
