# Generated by Django 4.2.6 on 2023-10-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPage', '0005_remove_blogcontent_slug_alter_blogcontent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcontent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
