# Generated by Django 4.2.6 on 2023-10-20 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPage', '0006_alter_blogcontent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcontent',
            name='Content',
            field=models.CharField(max_length=500),
        ),
    ]
