# Generated by Django 4.2.6 on 2023-10-21 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPage', '0007_alter_blogcontent_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcontent',
            name='Content',
            field=models.TextField(),
        ),
    ]
